version: '3'

services:

  mariadb:
    build: ./requirements/mariadb

    volumes:
      - db:/var/lib/mysql # dossier_local:dossier_container (les 2 sont liés)

    env_file:
      - ./.env

    networks:
      - docker_network
    restart:  always

  wordpress:
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress

    volumes:
      - wp:/var/www/html

    env_file:
      - ./.env

    networks:
      - docker_network

    restart:  always

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx

    env_file:
      - ./.env

    ports:
      - "443:443"

    networks:
      - docker_network
    
    volumes:
      - wp:/var/www/html

    restart:  always
    
networks:
  docker_network:
    driver: bridge

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o:    'bind'
      device: '/home/pierrot-inception/data/mariadb' # remplacer pierrot-inception par psaulnie quand nouvelle VM
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o:    'bind'
      device: '/home/pierrot-inception/data/wordpress' # remplacer pierrot-inception par psaulnie quand nouvelle VM
  