version: '3.3'

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o:    'bind'
      device: '/home/psaulnie/data/mariadb'
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o:    'bind'
      device: '/home/psaulnie/data/wordpress'

services:
  mariadb:
    container_name: mariadb
    build: 
      context: ./requirements/mariadb
      args:
          DB_NAME: wordpress
          MYSQL_USER: psaulnie
          MYSQL_PASSWORD: inception
          MYSQL_ROOT_PASSWORD: inception
    volumes:
      - db:/var/lib/mysql
    networks:
      - docker_network
    restart:  always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: 
      context: ./requirements/wordpress
      args:
          DB_NAME: wordpress
          MYSQL_USER: psaulnie
          MYSQL_PASSWORD: inception
          MYSQL_ROOT_PASSWORD: inception
    volumes:
      - wp:/var/www/html
    networks:
      - docker_network
    restart:  always

  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - docker_network
    volumes:
      - wp:/var/www/html
    restart:  always
    
networks:
  docker_network:
    driver: bridge

  