version: '3.3'

volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o:    'bind'
      device: '/home/psaulnie/data/mariadb'
  wp:
    driver: local
    driver_opts:
      type: 'none'
      o:    'bind'
      device: '/home/psaulnie/data/wordpress'

services:
  mariadb:
    environment:
      - DB_NAME=wordpress
      - MYSQL_USER=psaulnie
      - MYSQL_PASSWORD=inception
      - MYSQL_ROOT_PASSWORD=inception
    build: ./requirements/mariadb
    volumes:
      - db:/var/lib/mysql
    networks:
      - docker_network
    restart:  always

  wordpress:
    environment:
      - DB_NAME=wordpress
      - MYSQL_USER=psaulnie
      - MYSQL_PASSWORD=inception
      - MYSQL_ROOT_PASSWORD=inception
    depends_on:
      - mariadb
    build:
      context: ./requirements/wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - docker_network
    restart:  always

  nginx:
    depends_on:
      - wordpress
    build:
      context: ./requirements/nginx
    ports:
      - "443:443"
    networks:
      - docker_network
    volumes:
      - wp:/var/www/html
    restart:  always
    
networks:
  docker_network:
    driver: bridge

  